---
# System hostname
hostname: "{{ inventory_hostname }}"

# System-wide DNS
nameserver_timeout: 5
nameserver_attempts: 2
nameserver_rotate: false
nameservers: []

# Additional hosts in /etc/hots
additional_hosts: []

# Additional mount points
additional_mounts: []
#  - path: /mnt/example-data
#    src: /dev/sdf
#    fstype: xfs
#    opts: defaults,nofail

# Additional users
additional_users: []
# - name: test
#   command: Example user
#   groups: docker,users
#   sudo:
#     enable: yes
#     commands: ALL
#     nopassword: yes

# IPs to allow SSH through firewall (IPv4 or IPv6)
ssh_allowed_ips: []
# - 1.2.3.4

# Swap settings
swap_file: /var/ansible_swap
swap_size: 0 # in MB, none by default
sysctl_swappiness: 10 # default for Ubuntu is 60

# System reboot timeout (in seconds)
system_reboot_timeout: 3600

# Linode dyndns container image tag
linode_dyndns_container_version: latest

# Linode API token
linode_api_token: ""

# Linode domain
linode_dyndns_domain: example.com

# Hosts to update
linode_dyndns_hosts: []
# - server1
# - build

# DNS update interval (in minutes)
linode_dyndns_interval: 15

# Update AAAA (IPv6) record
linode_dyndns_ipv6: False
