---
- name: Install, enable, and start docker
  block:
    - name: Enable Amazon Linux Docker repo
      command: amazon-linux-extras enable docker

    - name: Install docker engine
      ansible.builtin.yum:
        name:
          - docker
        state: latest

    - name: Get system architecture
      ansible.builtin.command: uname -m
      register: uname

    - name: Download and install latest docker-compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ uname.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"
        owner: "root"
        group: "root"

    - name: Enable and start the docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
  become: yes
  tags:
    - docker
    - install
    - common
