# Called from mail.yaml, using include_tasks
---
- name: Ensure Heimdall data directory exists
  ansible.builtin.file:
    path: "{{ heimdall_data_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: yes
  tags:
    - files
    - heimdall
