# Called from mail.yaml, using include_tasks
---
- name: ALLOW UniFi traffic through firewall
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: any
  loop:
    - port: "{{ unifi_stun_port }}"
      proto: udp
    - port: "{{ unifi_control_port }}"
      proto: tcp
    - port: "{{ unifi_api_port }}"
      proto: tcp
    - port: "{{ unifi_http_port }}"
      proto: tcp
    - port: "{{ unifi_https_port }}"
      proto: tcp
    - port: "{{ unifi_speedtest_port }}"
      proto: tcp
    - port: "{{ unifi_discover_port }}"
      proto: udp
    - port: "{{ unifi_l2_discovery_port }}"
      proto: udp
  become: yes
  tags:
    - firewall
    - unifi
