---
- name: Ensure Portainer data directory exists
  file:
    path: "{{ portainer_data_path }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "0755"
  become: yes
  tags: portainer

- name: Create/Update Portainer docker container
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:{{ portainer_container_version }}"
    pull: yes
    restart_policy: unless-stopped
    ports:
      - "0.0.0.0:{{ portainer_port }}:{{ portainer_port }}"
    volumes:
      - "{{ portainer_docker_socket }}:/var/run/docker.sock"
      - "{{ portainer_data_path }}:/data"
    comparisons:
      "*": strict
  become: yes
  tags: portainer

- name: Allow Portainer port through firewall
  ufw:
    rule: allow
    port: "{{ portainer_port | string }}"
    proto: tcp
  become: yes
  tags:
    - portainer
    - firewall
