# Called from mail.yaml, using include_tasks
---
- name: Set system DNS
  block:
    - name: Stop and disable systemd-resolved service
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Check if /etc/resolv.conf is symlink
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: resolv_conf

    - name: Remove symlink for /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      when: resolv_conf.stat.islnk is defined and resolv_conf.stat.islnk

    - name: Remove idempotence flag from /etc/resolv.conf
      ansible.builtin.command: chattr -i /etc/resolv.conf
      when: resolv_conf.stat.islnk is defined and not resolv_conf.stat.islnk

    - name: Template out /etc/resolv.conf
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"

    - name: Add idempotence flag from /etc/resolv.conf
      ansible.builtin.command: chattr +i /etc/resolv.conf
  become: yes
  tags:
    - dns
    - common
