# Called from mail.yaml, using include_tasks
---
- name: Set system DNS
  block:
    - name: Stop and disable systemd-resolved service
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Remove idempotence flag from /etc/resolv.conf
      ansible.builtin.command: chattr -i /etc/resolv.conf

    - name: Template out /etc/resolv.conf
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"

    - name: Add idempotence flag from /etc/resolv.conf
      ansible.builtin.command: chattr +i /etc/resolv.conf
  become: yes
  tags:
    - dns
    - common
