# Called from mail.yaml, using include_tasks
---
- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}/docker.yaml"
    - default/docker.yaml
  tags:
    - docker
    - common

- name: Prune old docker containers, images, networks, volumes, and caches
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
  become: yes
  tags:
    - docker
    - cleanup
    - common
