# Called from mail.yaml, using include_tasks
---
- name: Remove legacy docker versions, install dependencies, and add the Apt repo
  block:
    - name: Remove legacy docker engine versions
      ansible.builtin.apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Install docker dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest

    - name: Get system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: dpkg

    - name: Add docker GPG signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present

    - name: Add docker Apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ dpkg.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        filename: docker
        state: present
      register: docker_repo

    - name: Update Apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: docker_repo.changed
  become: yes
  tags:
    - docker
    - repo
    - common

- name: Install, enable, and start docker
  block:
    - name: Install docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Enable and start the docker service
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
  become: yes
  tags:
    - docker
    - install
    - common

- name: Prune old docker containers, images, networks, volumes, and caches
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
  become: yes
  tags:
    - docker
    - cleanup
    - common
