---
- import_tasks: hostname.yaml
  tags:
    - common
    - hostname

# Pi-Hole controls it's own DNS, so always skip it
- include_tasks: dns.yaml
  when: nameservers | length > 0 and 'pihole' not in group_names
  tags:
    - common
    - dns

- include_tasks: hosts.yaml
  when: additional_hosts | length > 0
  tags:
    - common
    - hosts

- include_tasks: mounts.yaml
  loop: "{{ additional_mounts }}"
  tags:
    - common
    - mounts

- import_tasks: ssh.yaml
  tags:
    - common
    - ssh

- include_tasks: swap.yaml
  when: swap_size > 0
  tags:
    - common
    - swap

- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}/updates.yaml"
    - default/updates.yaml
  tags:
    - common
    - updates

- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}/packages.yaml"
    - default/packages.yaml
  tags:
    - common
    - packages

- import_tasks: docker.yaml
  tags:
    - common
    - docker

- include_tasks: groups.yaml
  loop: "{{ additional_groups }}"
  tags:
    - common
    - groups

- include_tasks: users.yaml
  loop: "{{ additional_users }}"
  loop_control:
    loop_var: user
  tags:
    - common
    - users
