---
# Will not create filesystems if they already exist
- name: Create additional filesystem(s)
  filesystem:
    dev: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    force: no
  become: yes
  with_items: "{{ additional_mounts }}"
  tags: mounts

# Mount path is automatically created if it does not exist
# Mounts are added to /etc/fstab automatically
- name: Add additional mount points
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  become: yes
  with_items: "{{ additional_mounts }}"
  tags: mounts
