---
# You will not be able to authenticate as root or with passwords
- name: Harden SSH server configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {
        regexp: "^PasswordAuthentication .+$",
        line: "PasswordAuthentication no",
      }
  become: yes
  register: sshd_config
  tags: ssh

- name: Reload SSH service
  systemd:
    name: sshd
    state: reloaded
  become: yes
  when: sshd_config.changed
  tags: ssh
