# Called from mail.yaml, using include_tasks
---
- name: Configure firewall for netmaker
  block:
    - name: Allow FORWARD traffic
      ansible.builtin.iptables:
        chain: FORWARD
        policy: ACCEPT

    - name: ALLOW netmaker traffic through firewall
      community.general.ufw:
        rule: allow
        direction: in
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        src: any
      loop:
        - port: "80"
          proto: tcp
        - port: "443"
          proto: tcp
        - port: "51821:51830"
          proto: udp
  become: yes
  tags:
    - firewall
    - netmaker
