# Called from mail.yaml, using include_tasks
---
# NetMaker uses docker-compose with several containers
- name: Update sysctl and then download and start netmaker
  block:
    - name: Set UDP Receive Buffer Size to 2500000
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: "2500000"
        sysctl_set: yes
        state: present
        reload: yes

    - name: Pull latest netmaker docker images
      command: docker compose pull
      args:
        chdir: "{{ netmaker_data_directory }}"

    - name: Start netmaker via docker-compose with new containers
      command: docker compose up -d --force-recreate
      args:
        chdir: "{{ netmaker_data_directory }}"
  become: yes
  tags:
    - install
    - netmaker
