---
- name: Include distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yaml"
    - default.yaml
  tags:
    - netmaker

- import_tasks: stop.yaml
  tags:
    - netmaker
    - stop

- import_tasks: files.yaml
  tags:
    - netmaker
    - files

- import_tasks: install.yaml
  tags:
    - netmaker
    - install
