---
- import_tasks: repo.yml
  tags:
    - repo
    - docker

- name: Install/Update docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  become: yes
  tags: docker

- name: Ensure docker service is enabled and running
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags: docker

- name: Install/Update docker package for Ansible modules
  pip:
    name: docker
    state: latest
    umask: "0022" # accessible globally
    executable: pip3
  become: yes
  tags:
    - docker
    - python

- name: Prune old docker containers, images, networks, volumes, and caches
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
