# Called from mail.yaml, using include_tasks
---
- name: Pull and start latest 'louislam/uptime-kuma:{{ kuma_container_version }}' docker container
  community.docker.docker_container:
    name: kuma
    image: "louislam/uptime-kuma:{{ kuma_container_version }}"
    pull: yes
    restart_policy: unless-stopped
    restart: yes
    network_mode: host # To access other container services
    volumes:
      - "{{ kuma_data_directory }}:/app/data"
    comparisons:
      "*": strict # recreate container on _any_ change
  become: yes
  tags:
    - install
    - kuma
