---
- import_tasks: files.yaml
  tags:
    - znc
    - files

- import_tasks: ssl.yaml
  when: znc_domain | length > 0
  tags:
    - znc
    - ssl

- import_tasks: install.yaml
  tags:
    - znc
    - install
