# Called from mail.yaml, using include_tasks
---
- name: Create Diffie-Hellman key and install script to sync certifcate
  block:
    - name: Generate ZNC Diffie-Hellman parameters
      community.crypto.openssl_dhparam:
        path: "{{ znc_data_directory }}/dhparam.pem"
        size: "{{ znc_dhparam_size }}"
        owner: "100"
        group: "101"

    - name: Install ZNC SSL certificate update script
      ansible.builtin.template:
        src: znc-ssl.sh.j2
        dest: "/usr/local/bin/znc-{{ znc_domain }}.sh"
        owner: root
        group: root
        mode: "0755"

    - name: Check for ZNC SSL certificate
      ansible.builtin.stat:
        path: "{{ znc_caddy_data_directory }}/caddy/certificates/acme-v02.api.letsencrypt.org-directory/{{ znc_domain }}/{{ znc_domain }}.crt"
      register: znc_cert

    # This may not always work; sometimes cert validation is slow
    - name: Wait 1 minute for ZNC certificate to generate
      ansible.builtin.pause:
        minute: 1
      when: znc_cert.stat.exists == False

    - name: Run ZNC SSL certificate update script
      ansible.builtin.command: "/usr/local/bin/znc-{{ znc_domain }}.sh"

    - name: Add SSL certificate update cronjob to run every Sunday morning
      ansible.builtin.cron:
        name: ZNC certificate update for {{ znc_domain }}
        minute: "30"
        hour: "4"
        weekday: "0" # Sunday
        job: "/usr/local/bin/znc-{{ znc_domain }}.sh"
  become: yes
  tags:
    - ssl
    - znc
