---
- import_tasks: files.yaml
  tags:
    - pihole
    - files

- import_tasks: unbound.yaml
  tags:
    - pihole
    - unbound

- import_tasks: dns.yaml
  tags:
    - pihole
    - dns

- import_tasks: install.yaml
  tags:
    - pihole
    - install

- import_tasks: sync.yaml
  when: pihole_sync | bool
  tags:
    - pihole
    - sync
