# Called from mail.yaml, using include_tasks
---
- name: Install and setup unbound
  block:
    - name: Ensure unbound config directory exists
      ansible.builtin.file:
        path: /etc/unbound/unbound.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure unbound anchor directories exists
      ansible.builtin.file:
        path: /var/lib/unbound
        state: directory
        owner: unbound
        group: unbound
        mode: "0755"

    - name: Download latest root hints
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.root
        dest: /var/lib/unbound/root.hints
        owner: unbound
        group: unbound
        mode: "0644"

    - name: Template out Pi-Hole configuration for unbound
      ansible.builtin.template:
        src: unbound.conf.j2
        dest: /etc/unbound/unbound.conf.d/pi-hole.conf
        owner: root
        group: root
        mode: "0644"

    - name: Install/Update unbound
      ansible.builtin.apt:
        name: unbound
        state: latest

    - name: Enable and start the unbound service
      ansible.builtin.systemd:
        name: unbound
        enabled: yes
        state: started
  become: yes
  tags:
    - unbound
    - pihole

- name: Remove resolvconf for unbound
  block:
    - name: Disable and stop the unbound-resolvconf service
      ansible.builtin.systemd:
        name: unbound-resolvconf
        enabled: no
        state: stopped
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  tags:
    - resolvconf
    - pihole
